# Diseño de experimentos

El diseño de experimentos consiste en idear una manera de generar nuevos conocimientos sobre relaciones causa-efecto entre variables de un problema científico. 

En este contexto, un **experimento** representa un cambio en las condiciones del problema de estudio. En el problema hay **variables independientes** y **variables dependientes**. Para el diseño de experimentos, también se consideran **niveles** y **tratamientos** de estas variables. Los niveles son los valores que toman las variables independientes, mientras que los tratamientos son los valores únicos que se asignan a cada combinación de niveles en el problema.

Por ejemplo, supongamos que se tiene un conjunto de datos como el que sigue.

In [1]:
import pandas as pd
import numpy as np

In [12]:
df = pd.DataFrame({
    "x1": np.random.randint(0, 3, size=20),
    'x2' : np.random.randint(0, 360, size=20)
})
df['y'] = df.x1 * np.deg2rad(df.x2) + np.random.random()
df

    x1   x2          y
0    0  246   0.935420
1    1  270   5.647809
2    0  196   0.935420
3    2  311  11.791368
4    0  354   0.935420
5    0  179   0.935420
6    1   59   1.965164
7    1  348   7.009166
8    0   96   0.935420
9    2  336  12.664033
10   0  140   0.935420
11   2  337  12.698939
12   0  346   0.935420
13   1  261   5.490729
14   2  142   5.892155
15   1   15   1.197219
16   1  337   6.817180
17   1  330   6.695007
18   0   44   0.935420
19   1  234   5.019491

Donde $x_1$ corresponde con valores aleatorios en el conjunto $\{0, 1, 2\}$, mientras que los valoes que puede tomar $x_2$ se encuentran en el rango $[0, 360] \in \mathbb{N}$. Para este caso, los niveles para $x_1$ podrían ser los valores $\{0, 1, 2\}$. Sin embargo, para $x_2$, se pueden especificar niveles en rangos que vayan en incrementos de cada $10, 20, 45\ldots$ La siguiente tabla muestra un ejemplo de estos niveles asociados a sus tratamientos.

In [13]:
n1 = [] # Niveles para x1
n2 = [] # Niveles para x2
t = [] # Tratamientos
for i in [0, 1, 2]:
    for j in [0, 45, 90, 135, 180, 225, 270, 315, 360]:
        n1.append(i)
        n2.append(j)
        t.append(i + j)

df_tratamientos = pd.DataFrame({
    'n1' : n1,
    'n2' : n2,
    't' : t
})

df_tratamientos

    n1   n2    t
0    0    0    0
1    0   45   45
2    0   90   90
3    0  135  135
4    0  180  180
5    0  225  225
6    0  270  270
7    0  315  315
8    0  360  360
9    1    0    1
10   1   45   46
11   1   90   91
12   1  135  136
13   1  180  181
14   1  225  226
15   1  270  271
16   1  315  316
17   1  360  361
18   2    0    2
19   2   45   47
20   2   90   92
21   2  135  137
22   2  180  182
23   2  225  227
24   2  270  272
25   2  315  317
26   2  360  362

La cantidad de tratamientos es la combinación de elementos de $n_1$ y $n_2$, es decir $2 \times 9 = 27$. Estas combinaciones de niveles, dados por los tratamientos, pueden procesarse mediante algún modelo y estudiar los resultados obtenidos de manera estadística. 

En el ámbito del aprendizaje automático, es común realizar un diseño de experimentos que incluya métricas de evaluación como variable de estudio.

## Tarea (10 puntos)

- Realizar un diseño de experimentos para tu problema de estudio en la que indiques los niveles y tratamientos de interés.
- Reporta en la metodología de tu artículo el diseño de experimentos que realizaste.